### ISSUE TITLE
Could you add the termcolors for two-firewatch-dark?

### ISSUE THREAD

**Issue by synergistics** [rakr/dotfiles#1]
Or point me to a place where I can find them? Thank you

**Comment by rakr** [comment]
Hi @synergistics,

Thanks for opening the issue, but can you be a little bit more specific as this can be understand in a plenty of different ways, are you looking for:

- iTerm2 theme, if that's the case this repo contains the two themes that I'm using (under the `term` folder)
- Native Mac Terminal theme, I haven't looked at that yet as I'm not using this app that often
- Adding 16 or 256 colors support to the theme itself, I'm currently looking at ways to improve the maintenance of this colorscheme and add a more accurate approximation for terminals that do not support true color.

Thanks for your reply.

**Comment by synergistics** [comment]
Oh, I meant the .itermcolors file for two-firewatch-dark. The file for firewatch light is in the term folder but the itermcolors for the dark version are not there.

**Comment by rakr** [comment]
OK got it, for the dark version I'm currently using `one-dark.itermcolors` that you'll find in my repo.
I did not took the time to create a specific version to match the colorscheme, but it is in my todo.
